# Generated by Django 4.2 on 2024-02-17 15:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profilemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True),
        ),
    ]
