# Generated by Django 4.2 on 2024-02-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='slug',
        ),
    ]
