# Generated by Django 4.2 on 2024-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profilemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='created_date',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='birth_date',
            field=models.DateField(auto_now=True),
        ),
    ]
