# Generated by Django 4.2 on 2024-02-20 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contact_contact_accounts_co_created_07cffc_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='accounts.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
