# Generated by Django 4.2 on 2024-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.profilemodel'),
        ),
    ]
