# Generated by Django 4.2 on 2024-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='crud.comment'),
        ),
    ]
