# Generated by Django 4.2 on 2024-02-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_post_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
