# Generated by Django 4.2 on 2024-02-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_post_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
