# Generated by Django 4.2 on 2024-02-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
