# Generated by Django 4.2 on 2024-02-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
